### PR TITLE
Use the new tryOnError method to avoid UndeliverableException if the …

### PR DESCRIPTION
**Pull request by AndrewBedscastle**
…subscriber is already disposed / exception cannot be delivered

Suggestion for
#63

### CODE REVIEW

**Comment by lemberh** [comment]
Support this fix.
In this thread you can find explanation for this fix https://github.com/ReactiveX/RxJava/issues/4880

**Comment by consp1racy** [comment]
tryOnError is still marked experimental, probably shouldn't depend on this

**Comment by kaushikgopal** [comment]
added my thinking on using the experimental `tryOnError` here -> https://github.com/instacart/truetime-android/issues/63#issuecomment-392622674

**Comment by kaushikgopal** [comment]
🙏 @AndrewBedscastle

**Pull request merged**
