### PR TITLE
Add callback interface to vanilla version

### PR DESCRIPTION
**Pull request by midaslefkowitz**

### CODE REVIEW

**Comment by kaushikgopal** [comment]
@midaslefkowitz apologies for the late action on this. The library underwent a significant change with 2.0 (disk caching and all, so i couldn't incorporate this PR). is this still something you'd like to add?

i'm not a big fan of adding the callback to the vanilla version, mostly because i want the vanilla version to be more of a shoot and forget kind of call.

what are your thoughts?

**Comment by midaslefkowitz** [comment]
I definitely understand the desire to have a shoot and forget call. The reason why I created the PR is that we were seeing crashes related to TrueTime not being initialized even though we had initialized on app load. Debugging revealed that the crash was due to the SNTP server not being available. Changing to another server helped but did not resolve the underlying issue, ie the request couldn't be completed for some reason and the client isn't informed of failure. Hence the callback PR where the client can decide what to do (like initiate a retry policy notify the user, etc).

To work around the current limitations what we do in our app is maintain a list of servers and when the app loads we kick off another thread that iterates over the list infinitely until it successfully connects. Not very pretty.

Another solution might be to  incorporate that approach into the TrueTime library itself. For example, _ntpHost could be an array of strings that the client can add to by exposing a new builder method like addHost(String host) and addHosts(String[] hosts), etc. 

What do you think?

**Comment by kaushikgopal** [comment]
Hmm, we're treading NTP territory at that point. If you notice the
accompanying library extension, we walk through the correct process for
doing something similar. We resolve the pool and shoot multiple calls to
each IP in that pool.

Quick aside: any reason you're not using the Rx extension ? It's far more
accurate and doesn't come with some of the problems you mention.

FYI i also just pushed a recent fix for 2.1 that should improve the success
rate of results.

**Comment by midaslefkowitz** [comment]
Not sure what you are referring to in the library extension, but regardless, we aren't only talking about NTP issues, just one example off the top of my head, bad connection. I think that a true set and forget library would open the api to the methods that I mentioned above.

Im not using the RX extension because I'm dealing with legacy code and it just isn't in the plans right now to migrate

**Comment by kaushikgopal** [comment]
i'm closing this issue for now. honestly the main reason to use this library is for the convenience in NTP that is only present at the moment with the Rx version.

the non-Rx version is almost like a bare bones call to make a single "SNTP" request (not NTP). 

if more folks feel strongly about this, happy to revisit.

**Pull request closed without merging**
