### PR TITLE
Very minor typo fixes.

### PR DESCRIPTION
**Pull request by shaunpanjabi**

### CODE REVIEW

**Comment by kaushikgopal** [comment]
curious why you closed this? look totally valid to me

**Comment by shaunpanjabi** [comment]
I closed it because I thought the repo was inactive. Should I reopen it?

**Comment by kaushikgopal** [comment]
Definitely still active :). Go ahead and open it please. I'll merge it

**Comment by shaunpanjabi** [comment]
Good to know it's still active 👍 . PR reopened.

**Comment by kaushikgopal** [comment]
🙏

**Pull request merged**
